listen:
  port: 19101
  # address: "10.1.2.3"
  # metrics_endpoint: "/metrics"

namespaces:
  - name: all_cost
    format: "$remote_addr $server_port $upstream_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $request_time $upstream_header_time"
    source:
      files:
        # - "/root/docker/nginx/logs/*.access.log"
        - /root/docker/nginx/logs/sy_443.access.log
    namespace_label: nginx
    print_log: true
    metrics_override:
      prefix: ""
    # labels:
    #   app: "application-one"
    #   environment: "production"
    #   foo: "bar"
    # histogram_buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]

    relabel:
      # - target_label: upstream_addr
      #   from: upstream_addr
      - target_label: request
        from: request
        split: 2
        separator: " "
        only_counter: false
        match: 
          - regexp: ".*.(htm|html|gif|jpg|png|css|map|js|ico|eot|svg|ttf|woff|woff2|pdf).*$"
            replacement: "/frontend-elements"
          - regexp: "/static.*"
            replacement: "/static-frontend-elements"
          - regexp: "(.*?)\\?.*"
            replacement: "$1?"
          - regexp: "^(.*)$"
            replacement: "$1"
      - target_label: server_port
        from: server_port
      - target_label: status
        from: status
        only_counter: true
        # match:
        #   - regexp: "^[^4][0-9]{2}$"
        #     replacement: "$1"

    # metrics_type: 1: Counter, 2: Gauge, 4: Histogram, 8: Summary, 二进制组合, 对应指标自动添加后缀: _total, _gauge, _hist, _summary
    others_metrics:
      body_bytes_sent:
        metrics_name: "http_response_size_bytes"
        metrics_help: "Total amount of transferred bytes"
        metrics_type: 1
      request_time:
        metrics_name: "http_response_time_seconds"
        metrics_help: "Time needed by NGINX to handle requests"
        metrics_type: 8
        max_age: 60s
        objectives:
          0.5: 0.05
          0.9: 0.01
          0.99: 0.001
      upstream_header_time:
        metrics_name: "upstream_header_time_seconds"
        metrics_help: "Time needed by upstream server to send response"
        metrics_type: 12
        histogram_buckets: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10]
        max_age: 60s
        objectives:
          0.5: 0.05
          0.9: 0.01
          0.99: 0.001

  - name: all_count
    format: "$remote_addr $server_port $upstream_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $request_time $upstream_header_time"
    source:
      files:
        # - "/root/docker/nginx/logs/*.access.log"
        - /root/docker/nginx/logs/sy_443.access.log
    print_log: true
    namespace_label: nginx
    metrics_override:
      prefix: ""
    # labels:
    #   app: "application-one"
    #   environment: "production"
    #   foo: "bar"
    # histogram_buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]

    relabel:
      - target_label: upstream_addr
        from: upstream_addr
      - target_label: request
        from: request
        split: 2
        separator: " "
        match: 
          - regexp: ".*.(htm|html|gif|jpg|png|css|map|js|ico|eot|svg|ttf|woff|woff2|pdf).*$"
            replacement: "/frontend-elements"
          - regexp: "/static.*"
            replacement: "/static-frontend-elements"
          - regexp: "(.*?)\\?.*"
            replacement: "$1?"
          - regexp: "^(.*)$"
            replacement: "$1"
      - target_label: server_port
        from: server_port