contact_links:
  - name: Frequently Asked Questions
    url: https://github.com/martin-helmich/prometheus-nginxlog-exporter#frequently-asked-questions
    about: Please check if your issue already has an answere here
